import os
import glob

import numpy as np
import pandas as pd
import streamlit as st

st.set_page_config(page_title="UK Electricity Demand Forecasting", layout="wide")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, "models")
PLOTS_DIR = os.path.join(BASE_DIR, "plots")

LSTM_PATH = os.path.join(MODELS_DIR, "best_lstm_model.h5")
SCALER_PATH = os.path.join(MODELS_DIR, "preprocessing.pkl")
ISO_PATH = os.path.join(MODELS_DIR, "isolation_forest.pkl")
META_PATH = os.path.join(MODELS_DIR, "preprocessing_metadata.pkl")
LSTM_FEATURE_SCALER_PATH = os.path.join(MODELS_DIR, "lstm_feature_scaler.pkl")
LSTM_TARGET_SCALER_PATH = os.path.join(MODELS_DIR, "lstm_target_scaler.pkl")


# ---------------------------------------------------------------------------
# Artifact loading — every load is guarded; missing files are collected, not raised
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading trained model artifacts...")
def load_artifacts():
    """Attempt to load the artifacts produced by ``src/main.py``.

    Returns a dict with keys ``lstm``, ``scaler``, ``iso_forest``, ``metadata``
    (each may be ``None``) and an ``errors`` list describing anything that could
    not be loaded. The app never crashes on a missing or corrupt artifact.
    """
    artifacts = {
        "lstm": None,
        "scaler": None,
        "iso_forest": None,
        "metadata": None,
        "lstm_feature_scaler": None,
        "lstm_target_scaler": None,
    }
    errors = []

    try:
        import joblib
    except ImportError as exc:  # pragma: no cover - joblib ships with scikit-learn
        errors.append(f"joblib is not installed: {exc}")
        joblib = None

    if joblib is not None:
        for key, path in (
            ("scaler", SCALER_PATH),
            ("iso_forest", ISO_PATH),
            ("metadata", META_PATH),
            ("lstm_feature_scaler", LSTM_FEATURE_SCALER_PATH),
            ("lstm_target_scaler", LSTM_TARGET_SCALER_PATH),
        ):
            try:
                if not os.path.exists(path):
                    raise FileNotFoundError(f"{os.path.basename(path)} not found in models/")
                artifacts[key] = joblib.load(path)
            except Exception as exc:  # noqa: BLE001 - surfaced to the UI, not fatal
                errors.append(f"Could not load {key} ({os.path.basename(path)}): {exc}")

    try:
        if not os.path.exists(LSTM_PATH):
            raise FileNotFoundError("best_lstm_model.h5 not found in models/")
        from tensorflow.keras.models import load_model

        # compile=False: inference only, and it avoids deserialising the
        # training loss/metrics (which fails for legacy HDF5 under Keras 3).
        artifacts["lstm"] = load_model(LSTM_PATH, compile=False)
    except Exception as exc:  # noqa: BLE001 - TF may also be absent; degrade gracefully
        errors.append(f"Could not load LSTM model (best_lstm_model.h5): {exc}")

    return artifacts, errors


def available_plots():
    if not os.path.isdir(PLOTS_DIR):
        return []
    return sorted(glob.glob(os.path.join(PLOTS_DIR, "*.png")))


def render_plot_gallery():
    plots = available_plots()
    if not plots:
        st.info("No pre-generated plots found in `plots/`.")
        return
    st.subheader("Pipeline visualisations")
    cols = st.columns(2)
    for i, path in enumerate(plots):
        with cols[i % 2]:
            st.image(path, caption=os.path.basename(path), use_container_width=True)


# ---------------------------------------------------------------------------
# Placeholder dashboard — shown when one or more artifacts are missing
# ---------------------------------------------------------------------------
def render_placeholder(errors):
    st.title("UK Electricity Demand Forecasting — Dashboard (placeholder)")
    st.warning(
        "Trained model artifacts were not found, so the live forecasting panel is "
        "disabled. The dashboard below is a placeholder — nothing has crashed."
    )

    with st.expander("Why am I seeing this?", expanded=True):
        st.markdown(
            "The Streamlit app loads artifacts that are generated by the training "
            "script. They are binary and are not committed to the repository, so on "
            "a fresh checkout they do not exist yet."
        )
        st.markdown("**Missing / unreadable artifacts:**")
        for err in errors:
            st.markdown(f"- {err}")

    st.markdown("### How to generate the artifacts")
    st.code(
        "cd uk-electricity-demand-forecasting\n"
        "pip install -r requirements.txt\n"
        "# place demanddata_2024.csv in the repo root, then:\n"
        "python src/main.py",
        language="bash",
    )
    st.markdown(
        "Running `src/main.py` writes these files into `models/`:\n"
        "- `best_lstm_model.h5` — trained two-layer LSTM\n"
        "- `preprocessing.pkl` — fitted `StandardScaler` for the baseline models\n"
        "- `isolation_forest.pkl` — fitted unsupervised anomaly detector\n"
        "- `preprocessing_metadata.pkl` — feature lists and lag configuration\n"
        "- `ridge.pkl`, `lasso.pkl`, `random_forest.pkl` — baseline regressors\n\n"
        "Reload this page once they exist and the live panel will activate."
    )

    st.divider()
    render_plot_gallery()


# ---------------------------------------------------------------------------
# Live dashboard — shown when the LSTM + Isolation Forest loaded successfully
# ---------------------------------------------------------------------------
def render_live(artifacts, errors):
    lstm = artifacts["lstm"]
    iso_forest = artifacts["iso_forest"]
    metadata = artifacts["metadata"] or {}

    st.title("UK Electricity Demand Forecasting — Dashboard")
    st.success("Trained artifacts loaded. Live forecasting is active.")
    if errors:
        with st.expander("Some optional artifacts could not be loaded"):
            for err in errors:
                st.markdown(f"- {err}")

    lag_1h_periods = metadata.get("lag_1h_periods", 2)
    lag_1d_periods = metadata.get("lag_1d_periods", 48)

    lstm_features = metadata.get(
        "lstm_features", ["HOUR", "WEEKDAY", "MONTH", "LAG_1H", "LAG_1D"]
    )
    n_lstm_features = len(lstm_features)

    # --- Forecast panel -----------------------------------------------------
    st.subheader("Next-period demand forecast (LSTM)")
    st.caption(
        f"The LSTM consumes the same {n_lstm_features} features as the baseline "
        f"models: {', '.join(lstm_features)}. LAG_1H is demand {lag_1h_periods} "
        f"half-hour periods ago; LAG_1D is {lag_1d_periods} periods / 24h ago."
    )
    c1, c2, c3 = st.columns(3)
    hour = c1.number_input("HOUR (0-23)", 0, 23, 18, 1)
    weekday = c2.number_input("WEEKDAY (0=Mon .. 6=Sun)", 0, 6, 2, 1)
    month = c3.number_input("MONTH (1-12)", 1, 12, 1, 1)
    c4, c5 = st.columns(2)
    lag_1h = c4.number_input("LAG_1H — demand ~1 hour ago (MW)", 0.0, 80000.0, 30000.0, 250.0)
    lag_1d = c5.number_input("LAG_1D — demand ~24 hours ago (MW)", 0.0, 80000.0, 31000.0, 250.0)

    feature_scaler = artifacts["lstm_feature_scaler"]
    target_scaler = artifacts["lstm_target_scaler"]

    if feature_scaler is None or target_scaler is None:
        st.info(
            "LSTM input/target scalers were not found. Re-run `python src/main.py` to "
            "regenerate `lstm_feature_scaler.pkl` and `lstm_target_scaler.pkl` — the "
            "forecast needs them to return real megawatt values instead of a flat signal."
        )
    elif st.button("Forecast next period", type="primary"):
        try:
            # Feature order must match training: HOUR, WEEKDAY, MONTH, LAG_1H, LAG_1D.
            # Scale the inputs the same way training did, predict in [0, 1] space,
            # then invert the prediction back to megawatts.
            x_raw = np.array([[hour, weekday, month, lag_1h, lag_1d]], dtype="float64")
            x_scaled = feature_scaler.transform(x_raw).reshape((1, n_lstm_features, 1))
            yhat_scaled = lstm.predict(x_scaled, verbose=0)
            yhat = float(target_scaler.inverse_transform(yhat_scaled).flatten()[0])
            st.metric("Forecast demand (next half-hour)", f"{yhat:,.0f} MW")
        except Exception as exc:  # noqa: BLE001
            st.error(f"Forecast failed: {exc}")

    st.divider()

    # --- Anomaly panel ----------------------------------------------------
    st.subheader("Infrastructure fault check (Isolation Forest)")
    if iso_forest is None:
        st.info("`isolation_forest.pkl` was not loaded, so the anomaly check is unavailable.")
    else:
        anomaly_features = metadata.get("anomaly_features", ["ND", "TSD", "ENGLAND_WALES_DEMAND"])
        st.caption(f"Detector trained on: {', '.join(anomaly_features)}")
        a1, a2, a3 = st.columns(3)
        nd = a1.number_input("ND — national demand (MW)", 0.0, 80000.0, 30000.0, 250.0)
        tsd = a2.number_input("TSD — transmission system demand (MW)", 0.0, 80000.0, 31000.0, 250.0)
        ew = a3.number_input("ENGLAND_WALES_DEMAND (MW)", 0.0, 80000.0, 28000.0, 250.0)
        if st.button("Run anomaly check"):
            try:
                row = np.array([[nd, tsd, ew]], dtype="float64")
                flag = int(iso_forest.predict(row)[0])
                score = float(iso_forest.decision_function(row)[0])
                if flag == -1:
                    st.error(f"ANOMALY flagged — decision score {score:.4f} (below the fitted threshold).")
                else:
                    st.success(f"Nominal — decision score {score:.4f}.")
            except Exception as exc:  # noqa: BLE001
                st.error(f"Anomaly check failed: {exc}")

    st.divider()
    render_plot_gallery()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    artifacts, errors = load_artifacts()
    core_ready = artifacts["lstm"] is not None
    if core_ready:
        render_live(artifacts, errors)
    else:
        render_placeholder(errors)


if __name__ == "__main__":
    main()
